import Head from 'next/head'
import Navbar from '../pages/components/navbar'
import Banner from '../pages/components/banner'
import { Container, Card, Row, Text, Grid } from "@nextui-org/react";
import { Image } from "@nextui-org/react";


export default function Home() {
  return (
      <div>
        <Head>
            <title>JACKO</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/pics/logo.png" />
        </Head>
        <Navbar/>
        <Container xl>
          <Card color="primary">
            <Row justify="center" align="center">
              <Text h6 size={40} color="white" css={{ m: 0 }}>
                Je m'appelle JACKLINE
              </Text>
            </Row>
            <Card>
              <Image
                width={320}
                height={400}  
                src="/pics/1.jpg"
                alt="Default Image"
                objectFit="cover"
              />
            </Card>
          </Card>
        </Container>
        <Banner/>
      </div>
  )
}
